### ISSUE TITLE
Scoop chamfer error

### ISSUE THREAD

**Issue by rox97** [kennetek/gridfinity-rebuilt-openscad#24]
<img width="1815" alt="Screenshot 2022-11-21 alle 12 42 28" src="https://user-images.githubusercontent.com/31823582/203042942-49818453-7996-4f75-aa68-b323714efb00.png">

Trying to print the bin with Scoop chamfer activated and 2 compartments, one of the two has an error.
Printing the one with one compartment, there is no error
(The printer settings in the customizer are the same that I used in prusaslicer)

<img width="1815" alt="Screenshot 2022-11-21 alle 12 47 49" src="https://user-images.githubusercontent.com/31823582/203044136-72ab3069-5ea9-4b6a-996f-62571b0d2657.png">

**Comment by kennetek** [comment]
![image](https://user-images.githubusercontent.com/40445044/203114981-24ba84bc-b2b5-435d-a63e-45067306790d.png)

I investigated, and I'm relieved to say that it looks like a slicer issue, not a model issue. The vase mode slicing for these bins is somewhat hacky, so it might need a bit of fiddling to get it to work. I did the same thing you did, and replicated the issue, but it was only one layer of error instead of multiple. I think it is because the diagonal seam, shown here, is intersecting that side, and it doesn't like that. I was able to get it to go away by increasing/decreasing the layer height in the slicer by 0.01 mm (0.29 or 0.31 if the OpenSCAD script has 0.3). I think that accidentally relocates the seam to a less critical part of the bin. As far as I know, there is not a way to specify what part of the bin has that diagonal seam.

**Comment by rox97** [comment]
Thank you. I see that actually the problem is probably the seam. I tried changing the layer height in the slicer but couldn't move the seam. I also tried changing the seam positioning option of prusaslicer or the seam painting function, but to no avail. Did you use prusaslicer or cura?

**Comment by rox97** [comment]
I also tried creating the stl with a layer height of 0.3 and in the slicer I get an error where it detects empty layers, even changing the layer height of +-0.01 in the slicer. 
Probably these two problems are not related to each other.
<img width="1815" alt="Screenshot 2022-11-21 alle 18 21 41" src="https://user-images.githubusercontent.com/31823582/203120599-46d0a54d-483a-4a7a-8203-a8287999076b.png">

**Comment by rox97** [comment]
I don't know how but i managed to change the seam position, but the problem is always there, even changing the slicer layer height
<img width="1815" alt="Screenshot 2022-11-21 alle 18 40 42" src="https://user-images.githubusercontent.com/31823582/203124190-5b781c36-9e7b-4296-acc6-05a4d38c2562.png">

**Comment by kennetek** [comment]
![image](https://user-images.githubusercontent.com/40445044/203126624-51789e0c-9d93-463d-b9f1-25235bf4befb.png)

Even though you got the seam on the back, I think the intersection with the middle divider is still messing with the slicing. Try to get the seam on the side walls. 

Other than that advice, I don't know if I can help much. I'm very interested in the solution, however.

**Comment by kennetek** [comment]
I recently looked at vase mode again, and realized the scoop chamfer was not touching the bottom of the bin. This may have been causing the issue? In one of my screenshots, the bottom of the chamfer is blue, as its bridging in air. I fixed that issue, but it needs to be tested to see if it slices better.

**Comment by rox97** [comment]
thanks for working on it! it seems that the modification solves some problems in the slicing, but there is still an error. it is probably caused by the position of the seam. I've also tried changing the position of the seam, both in the settings and using the seam paint function, and also changing the position of the object on the plane, but the result doesn't change. Later I try to print it to see what comes out
<img width="1904" alt="Screenshot 2023-02-06 alle 09 25 29" src="https://user-images.githubusercontent.com/31823582/216922329-8fa5d0d5-f85b-4025-8db6-3e696487e8fe.png">
<img width="1904" alt="Screenshot 2023-02-06 alle 09 25 36" src="https://user-images.githubusercontent.com/31823582/216922402-cad6a404-ef18-492e-b84f-3d43d64023cd.png">
<img width="1904" alt="Screenshot 2023-02-06 alle 09 25 42" src="https://user-images.githubusercontent.com/31823582/216922453-06c4380d-82b4-4b44-bcab-7bb3622371cc.png">

**Comment by rox97** [comment]
Forgive me, but I deleted the comment I had just written. I just noticed that I had set the height of the layers wrong. setting the right one, the slicing seems to give no problems. Thank you for working on it! I'll try to print later
