### ISSUE TITLE
Gridfinity-rebuilt-lite issue

### ISSUE THREAD

**Issue by mojamuto** [kennetek/gridfinity-rebuilt-openscad#249]
Hi, when I create a cube with gridfinity lite I can't stack one with another, and if I put a cube created with lite and another normal cube they are not the same.

![imagen](https://github.com/user-attachments/assets/d92a82d2-6f15-4e26-8c05-98ec55f99c2b)
the cube on the left is made with gridfinity-lite the one on the right with bins.

When passing it through orcaslicer the bridges are also made at different heights:
![imagen](https://github.com/user-attachments/assets/f6c0f84b-9782-4775-b290-0de249de0276)
the cube made with gridfinity lite makes the bridge 5 layers before the one built with gridfinity-bins (1mm difference)

my version of openscad is:
![imagen](https://github.com/user-attachments/assets/4ac871c0-4388-4a4e-9d1c-7c636308cd0c)

**Comment by EmperorArthur** [comment]
Thanks for the report.  
The bridging appears to be a separate issue, and I'd appreciate it if you would create a new issue just for that.

The bin on the left looks like it has something clipping into the base.  There should not be a flat overhang like you are seeing.  Does it occur on a 2x2 or 3x3 bin as well?

**Comment by mojamuto** [comment]
Yes, it occurs in all sizes.

![image](https://github.com/user-attachments/assets/bf88abd6-4aeb-40b7-8e6c-6edcc9896bbe)

the left one is 2x2 and the right one is 3x3.

I will open another problem just for the bridges, thank you very much.

**Comment by wjugit** [comment]
In case this helps....
I think if you just modify the following **translate** statement in **gridfinity_base_lite** (src/core/gridfinity-rebuilt-utility.scad)  the lite bins will no longer have that overhang.   

    //Bridging structure to tie the bases together
    difference() {
  // translate([0, 0, BASE_HEIGHT-top_bottom_thickness])
      **translate([0, 0, BASE_HEIGHT-top_bottom_thickness/2])**

**Comment by wjugit** [comment]
Note:  **translate([0, 0, BASE_HEIGHT])** produces an even cleaner exterior but not sure if there are any downsides across the interior of the bins

**Comment by Pytonballoon810** [comment]
I have fixed this issue.

**Comment by cporterbassett** [comment]
I tested to see if @EmperorArthur 's PR fixed this issue.

By my testing, it does not.

Using the file `gridfinity-rebuilt-lite.scad` in the root of the repo, I still get those same overhangs.  

Here is a screen shot:

![Image](https://github.com/user-attachments/assets/bb6063b3-3be2-480d-b83d-68582d8643fd)

**Comment by cporterbassett** [comment]
On the other hand, the [commit](https://github.com/Pytonballoon810/gridfinity-rebuilt-openscad/commit/db2ad54f8804b1b2e364bf23c59e1289df327578) by @Pytonballoon810 linked above worked for me.
